spring.application.name=ActiveAgeCore

server.port=8080

spring.data.mongodb.uri=${MONGO_URI}

server.error.include-message=always

jwt.expiration=86400000
jwt.secret=${JWT_SECRET:um-segredo-muito-grande-e-complexo-para-o-nosso-jwt-active-age-2026}